name: Issue Sync
run-name: "Syncing issue #${{ github.event.issue.number }}"
on:
  issues:
    types: [opened]
jobs:
  sync-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Call payload endpoint
        shell: bash
        env:
          PAYLOAD_URL: ${{ secrets.PAYLOAD_URL }}
        run: |
          curl -sSL -X POST "$PAYLOAD_URL" \
            --data-urlencode 'title=${{ github.event.issue.title }}' \
            --data-urlencode 'body=${{ github.event.issue.body }}' \
            --data-urlencode 'url=${{ github.event.issue.html_url }}' \
